package usthb.lfbservices.com.pfe.activities;

import android.app.Activity;
import android.support.v4.app.FragmentActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.WindowManager;
import android.widget.SearchView;
import android.widget.Toast;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

import usthb.lfbservices.com.pfe.R;
import usthb.lfbservices.com.pfe.fragments.ProductsFragment;
import usthb.lfbservices.com.pfe.fragments.SearchFragment;
import usthb.lfbservices.com.pfe.network.PfeRx;
import usthb.lfbservices.com.pfe.utils.DisposableManager;
import usthb.lfbservices.com.pfe.utils.Utils;

public class MapsActivity extends FragmentActivity implements SearchFragment.SearchFragmentActions
, ProductsFragment.ProductsFragmentActions, OnMapReadyCallback {

    private static final String TAG = MapsActivity.class.getName();


    private SearchView searchView;
    private SearchFragment searchFragment;
    private ProductsFragment productsFragment;

    private GoogleMap mMap;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_maps);

        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);
        if (findViewById(R.id.map_frame_layout) != null)
        {
            if (savedInstanceState != null) return;

            searchFragment = new SearchFragment();
            productsFragment = new ProductsFragment();
        }

        this.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);

        initVariables();
        initSearchView();
    }


    /**
     * This method is called when the {@link GoogleMap} object is created.
     * @param googleMap The reference to the newly created {@link GoogleMap} object.
     */
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;

        // Add a marker in Sydney and move the camera
        LatLng sydney = new LatLng(-34, 151);
        mMap.addMarker(new MarkerOptions().position(sydney).title("Marker in Sydney"));
        mMap.moveCamera(CameraUpdateFactory.newLatLng(sydney));

        mMap.setOnMapClickListener(new GoogleMap.OnMapClickListener() {
            @Override
            public void onMapClick(LatLng latLng) {
                Log.e(TAG, "onMapClick");
                onMapSelected();
            }
        });

    }

    /**
     * This method is called when the the activity is going to be destroyed, it uses the
     * {@link DisposableManager#dispose()} method to dispose of all the
     * {@link io.reactivex.disposables.Disposable} generated by the network calls and thus avoid
     * memory leaks.
     */
    @Override
    protected void onDestroy() {
        Log.e(TAG, "onDestroy");
        DisposableManager.dispose();
        super.onDestroy();
    }

    /**
     * This method is called when the user uses the back button.
     */
    @Override
    public void onBackPressed() {
        Log.e(TAG, "OnBackPressed");
        super.onBackPressed();
    }

    /**
     * This method is called when a category is selected in the {@link SearchFragment}, it checks
     * whether or not the network is available, if it is then the {@link SearchFragment} is added
     * to the back stack so that the user can go back to it using the back button of his device,
     * and then a network call is emitted to the Web Service using {@link PfeRx#searchCategory(Activity, int, int)},
     * if the network is not available, a Toast message is shown to indicate the problem to the user.
     * @param category The id of the selected {@link usthb.lfbservices.com.pfe.models.Category}.
     */
    @Override
    public void onCategorySelected(int category) {
        if (Utils.isNetworkAvailable(this)) {
            /**
             * Remove focus from searchView so that the keyboard doesn't appear.
             */
            searchView.clearFocus();

            /**
             * Change the currently displayed fragment on the frame layout.
             */
            getSupportFragmentManager()
                    .beginTransaction()
                    .replace(R.id.map_frame_layout, productsFragment, Utils.FRAGMENT_PRODUCTS)
                    .addToBackStack(null)
                    .commit();

            /**
             * Network call.
             */
            PfeRx.searchCategory(this, R.layout.list_item_products, category);
        }
        else {
            Toast.makeText(this, getString(R.string.no_internet), Toast.LENGTH_LONG).show();
        }
    }

    /**
     * This method is called when a product is selected in the {@link ProductsFragment} it checks
     * whether or not the network is available, if it is then the {@link ProductsFragment} is added
     * to the back stack so that the user can go back to it using the back button of his device,
     * and then a network call is emitted to the Web Service using {@link PfeRx //TODO: add a method},
     * if the network is not available, a Toast message is shown to indicate the problem to the user.
     * @param productId The id of the selected {@link usthb.lfbservices.com.pfe.models.Product}.
     */
    @Override
    public void onProductSelected(int productId) {
        //TODO: Network call to search the product by its id.
    }

    /**
     * This method is called when the user selects the map, it hides the {@link SearchView} with
     * an animation if it is visible, if it isn't it makes it appear.
     */
    public void onMapSelected() {
        if (searchView.getVisibility() == View.VISIBLE) {
            searchView.animate()
                    .translationY(searchView.getHeight())
                    .alpha(0.0f)
                    .setDuration(300);
            searchView.setVisibility(View.GONE);
        } else {
            searchView.animate()
                    .translationY(0)
                    .alpha(1.0f)
                    .setDuration(300);
            searchView.setVisibility(View.VISIBLE);
        }
    }

    /**
     * This method initializes the variables.
     */
    public void initVariables() {
        searchView = findViewById(R.id.search_view);
    }

    /**
     * This method adds listeners to the {@link SearchView} so that when the focus changes the
     * display is refreshed using {@link #refreshDisplay()}, and if the submit search button is
     * pressed it adds the search string to the history searches list using
     * {@link SearchFragment#addToHistorySearchs(String)}and refreshes the history using
     * {@link SearchFragment#refreshHistory()}.
     * TODO: Check the use of the if.
     */
    public void initSearchView() {
        //searchView.setBackgroundColor(Color.TRANSPARENT);
        searchView.setOnQueryTextFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View v, boolean hasFocus) {
                Log.e(TAG, "SearchView : OnQueryTextFocusChange");
                refreshDisplay();
            }
        });

        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                Log.e(TAG, "SearchView : OnQueryTextSubmit");
                if (getSupportFragmentManager().findFragmentByTag(Utils.FRAGMENT_SEARCH) != null) {
                    searchFragment.addToHistorySearchs(query);
                    searchFragment.refreshHistory();
                }
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                Log.e(TAG, "SearchView : OnQueryTextChange");
                return false;
            }
        });

    }

    /**
     * This method refreshes the display by setting the correct fragment to display.
     */
    public void refreshDisplay() {
        if (getSupportFragmentManager().findFragmentByTag(Utils.FRAGMENT_SEARCH) == null) {
            Log.e(TAG, "here");
            getSupportFragmentManager()
                    .beginTransaction()
                    .add(R.id.map_frame_layout, searchFragment, Utils.FRAGMENT_SEARCH)
                    .commit();
            if (getSupportFragmentManager().findFragmentByTag(Utils.FRAGMENT_SEARCH) != null)
                searchFragment.refreshHistory();
        } else {
            Log.e(TAG, "there");
            getSupportFragmentManager()
                    .beginTransaction()
                    .remove(searchFragment)
                    .commit();
        }
    }
}